- alias: test
  trigger:
    - platform: state
      entity_id: input_boolean.mytest
  action:
    - service: script.sonos_say
      data:
        sonos_entity: media_player.kitchen
        volume: 0.9
        message: 'Your husband coming home!'
        delay: '00:00:05'

#ios
- alias: Reset meds taken
    trigger:
      platform: state
      entity_id: input_boolean.meds_taken
      to: 'on'
      for:
        hours: 16
    action:
      service: input_boolean.turn_off

  - alias: Mark meds as taken from notification
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 'MARK_MEDS_TAKEN'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.meds_taken

  - alias: Meds have not been taken weekday
    trigger:
      platform: time
      after: '20:00:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.meds_taken
          state: 'off'
        - condition: state
          entity_id: input_boolean.meds_reminder
          state: 'on'
    action:
      - service: notify.ios_ashlee
        data:
          title: "Birth Control"
          message: "Ashlee's BC has not been taken!"
          data:
            push:
              category: 'MEDS_NOT_TAKEN'

###### automation for turning on the alarm ######
- id: alarm_clock_activated
  alias: Alarm Clock Activated
  hide_entity: False
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.alarm_clock_time_long.state }}'
    condition:
      condition: state
      entity_id: input_boolean.alarm_clock_status
      state: 'on'
    action:
    - service: script.turn_on
      entity_id: script.s_alarm_clock_wake_up
    - service: notify.ios_alvaro
      data:
        title: "Alarm Clock"
        message: "It's Time For You To Wake Up!"
        data:
          push:
            sound: "US-EN-Alexa-Good-Morning.wav"
            badge: 0
            category: 'alarmclock'

###### awake actionable notification pushed ######
- id: a_alarm_clock_awake_action
  alias: alarm clock awake action
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
    actionName: AWAKE
  action:
    service: script.turn_on
    entity_id: script.s_alarm_clock_awake

###### snooze actionable notification pushed ######
- id: a_alarm_clock_snooze_action
  alias: alarm clock snooze action
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
    actionName: SNOOZE
  action:
    service: script.turn_on
    entity_id: script.s_alarm_clock_snooze
