- alias: Notification Audio - Test
  trigger:
    - platform: state
      entity_id: input_boolean.test_audio_notification
      from: 'off'
      to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.say
      data_template:
        variables:
          master: 'media_player.kitchen'
          where: 'media_player.media_player.kitchen'
          volume: '.6'
          what: >
            {% set hour = now().strftime("%H") %}
            {% set weekday_full_name = now().strftime("%A") %}
            {% set month_full_name = now().strftime("%B") %}
            {% set day = now().strftime("%-d") %}
            {% set weekday = now().strftime("%w") %}
            {% if hour | int < 12 %}
            Good morning.
            {% elif hour | int < 18 %}
            Good afternoon.
            {% else %}
            Good evening.
            {% endif %}
            This is a test of the text to speech engine.
            Today is {{ weekday_full_name }} {{ month_full_name }} the
              {% if day | int == 1 or day | int == 21 or day | int == 31 %}
                {{ day }}st
              {% elif day | int == 2 or day | int == 22 %}
                {{ day }}nd
              {% elif day | int == 3 or day | int == 23 %}
                {{ day }}rd
              {% else %}
                {{ day }}th
              {% endif %}.
            It's currently {{states.sensor.dark_sky_summary.state}} and {{states.sensor.dark_sky_temperature.state|round}} degrees in REDACTED. Today will be {{states.sensor.dark_sky_hourly_summary.state|replace(".", "")}}, with a high of {{states.sensor.dark_sky_daily_high_temperature.state|round}} degrees.
            End of text to speech test.
    - delay: '00:00:01'
    - service: homeassistant.turn_off
      entity_id: input_boolean.test_audio_notification

#ios
- alias: Notify iOS Birth Control
  trigger:
    platform: time
    at: '18:30:00'
  action:
    service: notify.ashlee_phone
    data:
      message: "Please take the Birth Control"
      data:
        push:
          badge: 5

- alias: Set Sonos Alarm
  trigger:
    - platform: state
      entity_id: input_boolean.alarm_clock_status
      to: 'on'
  action:
    service: media_player.sonos_update_alarm
    data_template:
      entity_id: media_player.kitchen
      alarm_id: 4
      time: '{{ states.sensor.alarm_clock_time.state }}'
      enabled: true
- alias: Disable Sonos Alarm
  trigger:
    - platform: state
      entity_id: input_boolean.alarm_clock_status
      to: 'off'
  action:
    service: media_player.sonos_update_alarm
    data_template:
      entity_id: media_player.kitchen
      alarm_id: 4
      enabled: false
