#School Schedule
- alias: Reminder MA113
    trigger:
      platform: time
      after: '11:20:00'
    condition:
      condition:
      weekday:
        - mon
        - wed
        - fri
    action:
    - service: media_player.sonos_snapshot
      data_template:
        entity_id: media_player.kitchen
    - service: tts.google_say
      entity_id: media_player.kitchen
      data_template:
        language: "en"
        message: "Alvaro, your MA113 will start at 12:20, start getting ready"
#School Schedule
- alias: Reminder CS112
    trigger:
      platform: time
      after: '08:30:00'
    condition:
      condition:
      weekday:
        - tue
        - thu
    action:
    - service: media_player.sonos_snapshot
      data_template:
        entity_id: media_player.kitchen
    - service: tts.google_say
      entity_id: media_player.kitchen
      data:
        language: "en"
        message: "Alvaro, your CS112 will start at 9:30, start getting ready"

- alias: Reminder MA150
    trigger:
      platform: time
      after: '10:00:00'
    condition:
      condition:
      weekday:
        - tue
        - thu
    action:
    - service: media_player.sonos_snapshot
      data_template:
        entity_id: media_player.kitchen
    - service: tts.google_say
      entity_id: media_player.kitchen
      data:
        language: "en"
        message: "Alvaro, your MA150 will start at 11, start getting ready"

- alias: Reminder CS131
    trigger:
      platform: time
      after: '14:30:00'
    condition:
      condition:
      weekday:
        - tue
        - thu
    action:
    - service: media_player.sonos_snapshot
      data_template:
        entity_id: media_player.kitchen
    - service: tts.google_say
      entity_id: media_player.kitchen
      data:
        language: "en"
        message: "Alvaro, your CS131 will start at 3:30, start getting ready"

#ios
- alias: Reset meds taken
    trigger:
      platform: state
      entity_id: input_boolean.meds_taken
      to: 'on'
      for:
        hours: 4
    action:
      service: input_boolean.turn_off

  - alias: Mark meds as taken from notification
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: 'MARK_MEDS_TAKEN'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.meds_taken

  - alias: Meds have not been taken weekday
    trigger:
      platform: time
      after: '20:00:00'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.meds_taken
          state: 'off'
        - condition: state
          entity_id: input_boolean.meds_reminder
          state: 'on'
    action:
      - service: notify.ios_ios_ashlee
        data:
          title: "Birth Control"
          message: "Ashlee's BC has not been taken!"
          data:
            push:
              category: 'MEDS_NOT_TAKEN'

###### automation for turning on the alarm ######
- id: alarm_clock_activated
  alias: Alarm Clock Activated
  hide_entity: False
  trigger:
    platform: template
    value_template: '{{ now.time().strftime("%-H") == states.input_number.alarm_clock_hour.state and now.time().strftime("%-M") == states.input_number.alarm_clock_minute.state }}'
  condition:
    condition: state
    entity_id: input_boolean.alarm_clock_status
    state: 'on'
  action:
    - service: script.turn_on
      entity_id: script.s_alarm_clock_wake_up
    - service: notify.ios_ios_alvaro
      data:
        title: "Alarm Clock"
        message: "It's Time For You To Wake Up!"
        data:
          push:
            badge: 0
            category: 'alarmclock'

###### awake actionable notification pushed ######
- id: a_alarm_clock_awake_action
  alias: alarm clock awake action
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
    actionName: AWAKE
  action:
    service: script.turn_on
    entity_id: script.s_alarm_clock_awake

###### snooze actionable notification pushed ######
- id: a_alarm_clock_snooze_action
  alias: alarm clock snooze action
  initial_state: true
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
    actionName: SNOOZE
  action:
    service: script.turn_on
    entity_id: script.s_alarm_clock_snooze

#Devices Off When Away
- alias: Lights Off When Away
  trigger:
    platform: state
    entity_id: group.alltrackers
    to: 'not_home'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: group.switches
