homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 42.370113
  longitude: -71.073655
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2.7
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include customize.yaml


discovery:
# Enables the frontend
frontend:
hassio:
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: hass-ac.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
media_player:
  - platform: sonos
    hosts: 10.0.0.144

#apiai: !include apiai.yaml
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#iOs
ios: #!include ios.yaml

#Device Tracker
device_tracker:
  - platform: bluetooth_tracker

# Weather Prediction
sensor:
  - platform: yr

  - platform: google_travel_time
    api_key: AIzaSyC_qJ81D5L7d6k5MPVWB3YGNlImBzscED4
    origin: 1 Leighton St Cambridge
    destination: 675 Commonwealth St Brookline
    name: 'ETA Home-BU'

  - platform: google_travel_time
    api_key: AIzaSyC_qJ81D5L7d6k5MPVWB3YGNlImBzscED4
    origin: 1 Leighton St Cambridge
    destination: 415 South St, Waltham, MA 02453
    name: 'ETA Home-Brandeis'

  - platform: template
    sensors:
      alarm_clock_time:
        friendly_name: 'Alarm Time'
        icon_template: 'mdi:alarm'
        value_template: '{{ "%0.02d:%0.02d" | format(states.input_number.alarm_clock_hour.state | int, states.input_number.alarm_clock_minute.state | int ) }}'
      alarm_clock_fade_in_minutes:
        friendly_name: 'Fade In (Minutes)'
        icon_template: 'mdi:gradient'
        value_template: '{{ states.input_number.alarm_clock_fade_in_minutes.state | int }}'

# Text to speech
tts:
  - platform: amazon_polly
    aws_access_key_id: 'AKIAJXPRNJRVTJHJN6DQ'
    aws_secret_access_key: '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'
    region_name: 'us-east-1'
    voice: Ivy

#Automations
automation: !include automation.yaml

#Scripts
script: !include script.yaml

#Inputs
#input_select: !include selects.yaml

#Booleans
input_boolean: !include booleans.yaml

#Sliders
input_number: !include sliders.yaml

#Groups
group: !include groups.yaml

#Notifications
#notify:
  #- platform: ios
    #name: ios_alvaro
    #target: f729c78b-c577-3876-b34f-1fcffc8fb067

#Shell commands
shell_command: !include shell_command.yaml

#MQTT
#mqtt:
  #broker: m13.cloudmqtt.com
  #port: 10944
  #client_id: homeassistant
  #keepalive: 60
  #username: !secrets broker_user
  #password: !secrets broker_pass
  #birth_message:
  #  topic: 'hass/status'
  #  payload: 'online'
  #  qos: 1
  #  retain: true
  #will_message:
  #  topic: 'hass/status'
   # payload: 'offline'
   # qos: 1
   # retain: true


#Wink
#wink:
#  email: !secret wink_user
#  password: !secret wink_pass
#Alexa
#alexa:
  #intents: !include_dir_merge_named alexa
