homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 42.370113
  longitude: -71.073655
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2.7
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

  customize: !include customize.yaml

http:
  api_password: !secret mainpass

# Checks for available updates
updater:

switch:
  - platform: command_line
    switches:
      living_room_tv:
        friendly_name: Living Room TV
        command_on: "/usr/bin/curl -k -H \"Content-Type: application/json\" -H \"AUTH: Zxwxlh0ada\" -X PUT -d '{\"KEYLIST\": [{\"CODESET\": 11,\"CODE\": 1,\"ACTION\":\"KEYPRESS\"}]}' https://10.0.0.18:9000/key_command/"
        command_off: "/usr/bin/curl -k -H \"Content-Type: application/json\" -H \"AUTH: Zxwxlh0ada\" -X PUT -d '{\"KEYLIST\": [{\"CODESET\": 11,\"CODE\": 0,\"ACTION\":\"KEYPRESS\"}]}' https://10.0.0.18:9000/key_command/"
        command_state: "/usr/bin/curl -k -H \"Content-Type: application/json\" -H \"AUTH: Zxwxlh0ada\" -X GET https://10.0.0.18:9000/state/device/power_mode"
        value_template: >
          {% if value_json.ITEMS.0.VALUE == 1 %}
            true
          {% else %}
            false
          {% endif %}

# Discover some devices automatically
media_player:
  - platform: sonos
    hosts: 10.0.0.144

  - platform: vizio
    host: 10.0.0.18
    access_token: Zxwxlh0ada

#apiai: !include apiai.yaml
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
discovery:
# View all events in a logbook
logbook:

# Track the sun
sun:

#iOs
ios: #!include ios.yaml

#Device Tracker
device_tracker:
  - platform: owntracks

# Weather Prediction
sensor:
  - platform: yr

  - platform: google_travel_time
    api_key: AIzaSyC_qJ81D5L7d6k5MPVWB3YGNlImBzscED4
    origin: 1 Leighton St Cambridge
    destination: 675 Commonwealth St Brookline
    name: 'ETA Home-BU'

  - platform: google_travel_time
    api_key: AIzaSyC_qJ81D5L7d6k5MPVWB3YGNlImBzscED4
    origin: 1 Leighton St Cambridge
    destination: 415 South St, Waltham, MA 02453
    name: 'ETA Home-Brandeis'

  - platform: template
    sensors:
      alarm_clock_hour:
        value_template: '{{ states.input_number.alarm_clock_hour.state | int }}'
      alarm_clock_minutes:
        value_template: '{{ states.input_number.alarm_clock_minutes.state | int }}'
      alarm_clock_time:
        value_template: >-
          {{ states.sensor.alarm_clock_hour.state }}:
          {%- if states.sensor.alarm_clock_minutes.state|length == 1 -%}
            0
          {%- endif -%}
            {{ states.sensor.alarm_clock_minutes.state }}
      alarm_clock_time_long:
        value_template: >-
          {% if states.sensor.alarm_clock_hour.state|length == 1 -%}
            0
          {%- endif -%}
            {{ states.sensor.alarm_clock_hour.state }}:
          {%- if states.sensor.alarm_clock_minutes.state|length == 1 -%}
            0
          {%- endif -%}
            {{ states.sensor.alarm_clock_minutes.state }}

# Text to speech
tts:
  - platform: google

#Automations
#automation: !include automation.yaml

#Scripts
script: !include script.yaml

#Inputs
#input_select: !include selects.yaml

#Booleans
input_boolean: !include booleans.yaml

#Sliders
input_number: !include input_number.yaml

#Groups
group: !include groups.yaml

#Notifications
notify:
  - platform: ios
    name: ios_alvaro
    target: f729c78b-c577-3876-b34f-1fcffc8fb067

#Shell commandss
shell_command: !include shell_command.yaml


wink:


#MQTT
#mqtt:
  #broker: m13.cloudmqtt.com
  #port: 10944
  #client_id: homeassistant
  #keepalive: 60
  #username: !secrets broker_user
  #password: !secrets broker_pass
  #birth_message:
  #  topic: 'hass/status'
  #  payload: 'online'
  #  qos: 1
  #  retain: true
  #will_message:
  #  topic: 'hass/status'
   # payload: 'offline'
   # qos: 1
   # retain: true


#Wink
#wink:
#  email: !secret wink_user
#  password: !secret wink_pass
#Alexa
#alexa:
  #intents: !include_dir_merge_named alexa
